# Generated by Django 4.2.7 on 2024-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='moral',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
